version: '3.8'

services:
   postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    env_file:
      - ./docker.env
    ports:
      - "5432:5432"
    volumes:
      - go_postgres_data:/var/lib/postgresql/data
   pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    env_file:
      - ./docker.env
    ports:
      - "5050:80"
    depends_on:
      - postgres
   server:
    build: .
    ports: 
      - "8080:8080"
    env_file:
      - .env
    restart: always
    depends_on:
      - postgres
    environment:
      - ENV=production
volumes:
  go_postgres_data:
    driver: local